server:
  port: 10009
  tomcat:
    max-http-form-post-size: 100MB
spring:
  datasource:
    url: jdbc:mysql://172.20.0.140:3306/cardb?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: huangjiaxuan
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
  application:
    name: CarNavigation
security:
  basic:
    enabled: false
